config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings

  resources :email_templates do
    collection do
      get 'select', to: 'email_templates#select'
    end

    member do
      get 'adapt', to: 'email_templates#adapt'
      post 'adapt', to: 'email_templates#notify'
    end
  end

  resources :confirmation_emails

  root 'bookings#index'
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :bigint           not null, primary key
#  category   :string
#  email      :string
#  items      :string
#  name       :string
#  purpose    :text
#  quantity   :integer
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Booking < ApplicationRecord
  # category mapping
  # CATEGORIES = %i[electronics].freeze
  # enum category: CATEGORIES

  STATUSES = %i[pending approved rejected].freeze
  enum status: STATUSES

  validates :name, presence: true
  validates :email, presence: true
  validates :category, presence: true
  validates :items, presence: true
  validates :status, presence: true
  validates :quantity, numericality:{greater_than: 0}
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # Disable authenticity token verification for now
  before_action :authenticate_user!, :except => [:create]
  skip_before_action :verify_authenticity_token

  def index
    @bookings = Booking.all
  end

  def create
    booking = Booking.new booking_params

    if booking.save
      #placeholder
    else
      #placeholder
    end
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update status_param
      if @booking.status == 'rejected'
        redirect_to select_email_templates_path(booking_id: @booking.id),
                    notice: "Succesfully rejected booking, please select email template"

      elsif @booking.status == 'approved'
        redirect_to select_email_templates_path(booking_id: @booking.id),
                    notice: "Succesfully approved booking, please select email template"
      end
    else
      redirect_to bookings_path,
                  alert: "Failed to update booking status"
    end
  end

private
  def booking_params
    to_hash('[' + get_param_values + ']')
  end

  def status_param
    params.permit(:status)
  end

  def to_hash(param)
    result = Hash.new
    hashes = JSON.parse(param)
    
    hashes.each do |d|
      
      unless d['name'] == 'g-recaptcha-response'
        key = d['name'].sub('id:', '')
                       .sub('ItemQuantity', 'quantity')
                       .sub('PurposeofRental', 'purpose')
        value = d['value'] 
        if key == 'category'
          value = value.downcase
        end

        result[key] = value
      end
    end

    return init_status result
  end

  def init_status(params)
    params[:status] = 'pending'

    params
  end

  def get_param_values()
    hash_to_be_filtered = params.to_unsafe_h
    denilized_hash = denilize(hash_to_be_filtered, 'values')
    reversed_hash = denilized_hash.invert
    params_to_be_filtered = ActionController::Parameters.new(reversed_hash)

    filtered_params = params_to_be_filtered.require(:values)
  end

  def denilize(h, nil_replacement)
    h.each_with_object({}) { |(k,v),g|
      g[k] = (Hash === v) ?  denilize(v) : v.blank? ? nil_replacement : v }
  end
end

app/helpers/bookings_helper.rb
require 'json'
require 'net/http'

module BookingsHelper
  def get_request
    uri = URI("http://www.example.com")
    res =  Net::HTTP.get(uri)
    request = JSON.parse(res)
    request = to_hash(request)

    Booking.create( name: request["id:name"], 
                    email: request["id:email"], 
                    category: request["category"].downcase,
                    items: request["items"],
                    quantity: request["ItemQuantity"],
                    purpose: request["PurposeofRental"])
  end

  def to_hash(hashes)
    result = Hash.new
    
    hashes.each do |d|
      unless d["name"] == "g-recaptcha-response"
        result[d["name"]] = d["value"]
      end
    end

    return result
  end
end

app/views/bookings/index.html.erb
<div class="container-fluid no-padding">
  <h1>Booking List</h1>
</div>

<div class="col-md-12 col-sm-12">
  <div class="table-responsive">
    <div class="col-md-12 scrollable">
      <table class="table">
        <tr>
          <th class="name">Name</th>
          <th class="email">Email</th>
          <th class="category">Category</th>
          <th class="items">Items</th>
          <th class="quantity">Quantity</th>
          <th class="purpose">Purpose</th>
          <th class="created-at">Requested At</th>
          <th class="updated-at">Updated At</th>
          <th class="status">Status</th>
          <th class="edit">Edit</th>
        </tr>
        <% @bookings.sort_by(&:created_at).reverse.each do |b| %>
          <tr>
            <td class="name"><%= b.name %></td>
            <td class="email"><%= b.email %></td>
            <td class="category"><%= b.category.capitalize %></td>
            <td class="items"><%= b.items %></td>
            <td class="quantity"><%= b.quantity %></td>
            <td class="purpose"><%= simple_format b.purpose %></td>
            <td class="created-at"><%= b.created_at.strftime("%d %b %Y") %></td>
            <td class="updated-at"><%= b.updated_at.strftime("%d %b %Y") %></td>
            <td class="status"><%= b.status.capitalize %></td>
            <% if b.status == "approved" %>
              <td class="edit"><%= form_tag(booking_path(b.id), method: "patch") do %>
              <%= button_tag("Reject", name: 'status', value: :rejected,
                type: 'submit', class: "btn booking-btn btn-danger")%>
              <% end %> </td>  
            <% elsif b.status == "rejected" %>
              <td class="edit"><%= form_tag(booking_path(b.id), method: "patch") do %>
              <%= button_tag("Approve", name: 'status', value: :approved,
                  type: 'submit', class: "btn booking-btn btn-success")%>
              <% end %> </td> 
            <% else %>
              <td class="edit"><%= form_tag(booking_path(b.id), method: "patch") do %>
              <%= button_tag("Approve", name: 'status', value: :approved,
                  type: 'submit', class: "btn booking-btn btn-success")%>
              <% end %>
              <p></p>
              <%= form_tag(booking_path(b.id), method: "patch") do %>
              <%= button_tag("Reject", name: 'status', value: :rejected,
                  type: 'submit', class: "btn booking-btn btn-danger")%>
              <% end %></td> 
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div class="footer" style="text-align: center">
  <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-large btn-light", style: "background-color: #ffaaaa", method: :delete %>
  <%= link_to 'Email templates', email_templates_path, class: "btn btn-large btn-light", style: "background-color: #3399ff", method: :get %>
</div>