config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings

  resources :email_templates do
    collection do
      get 'select', to: 'email_templates#select'
    end

    member do
      get 'adapt', to: 'email_templates#adapt'
      post 'adapt', to: 'email_templates#notify'
    end
  end

  resources :confirmation_emails

  root 'bookings#index'
end

app/models/email_template.rb
# == Schema Information
#
# Table name: email_templates
#
#  id         :bigint           not null, primary key
#  content    :text
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EmailTemplate < ApplicationRecord
  validates :content, presence: true
  validates :name, presence: true
end

app/controllers/email_template_controller.rb
class EmailTemplateController < ApplicationController
  def index
    @templates = EmailTemplate.all
  end

  def create
    @template = EmailTemplate.new template_params

    if @template.save
      redirect_to email_template_index_path,
                  notice: 'Template succesfully saved!'  
    else
      redirect_to email_template_index_path,
                  alert: 'Could not save template!'
    end
  end

  private

  def template_params
    params.require(:email_template).permit(:content)
  end
end

app/controllers/email_templates_controller.rb
class EmailTemplatesController < ApplicationController
  def index
    @templates = EmailTemplate.all
  end

  def new
    @template = EmailTemplate.new
  end

  def create
    @template = EmailTemplate.new template_params

    if @template.save
      redirect_to email_templates_path,
                  notice: 'Template succesfully saved!'  
    else
      redirect_to email_templates_path,
                  alert: 'Could not save template!'
    end
  end

  def show
    @template = EmailTemplate.find params[:id]
  end

  def select
    @templates = EmailTemplate.all
    @booking_id = params[:booking_id]
  end

  private

  def template_params
    params.require(:email_template).permit(:content, :name)
  end
end

app/helpers/email_template_helper.rb
module EmailTemplateHelper
end

app/views/email_templates/index.html.erb
<div class="container-fluid no-padding">
  <h1>Template List</h1>
</div>

<div class="header" style="text-align: center">
  <%= link_to 'New Template', new_email_template_path, class: "btn btn-large btn-light", style: "background-color: #3399ff", method: :get %>
</div>

<div class="col-md-12 col-sm-12">
  <div class="table-responsive">
    <div class="col-md-12 scrollable">
      <table class="table template-table">
        <tr>
          <th class="name">Name of Template</th>
          <th class="content">Content Preview</th>
          <th class="details"></th>
        </tr>
        <% @templates.sort_by(&:created_at).reverse.each do |t| %>
          <tr>
            <td class="name"><%= t.name %></td>
            <td class="content"><%= truncate(t.content, length: 80) %></td>
            <td class="details"><%= link_to 'Show more', email_template_path(t) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div class="footer" style="text-align: center">
  <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-large btn-light", style: "background-color: #ffaaaa", method: :delete %>
  <%= link_to 'Booking requests', bookings_path, class: "btn btn-large btn-light", style: "background-color: #3399ff", method: :get %>
</div>

app/views/email_templates/new.html.erb
<div class="container-fluid no-padding">
  <h1>Create New Email Template</h1>
</div>

<div class="col-md-12 col-sm-12">
  <div class="btn-container">
    <div><%= button_to("Back To Email Template List", email_templates_path, method: "get", class: "btn btn-large btn-light") %></div>
  <div>

  <%= form_for @template do |t|%>
    <div class="table-responsive-lg new-email-template-table">
      <table>
        <tr>
          <td class="td-container name"><b>Name of Template</b></td>
          <td><%= t.text_field(:name, class: "form-control") %></td>
        </tr>

        <tr>

          <td class="td-container content"><b>Content</b></td>
          <% content_place_holder = "Please type the email template here"%>
          <td>
            <%= t.text_area(:content, size: "100x10", placeholder: content_place_holder, class: "form-control") %>
          </td>
        </tr>

        <tr>
          <td colspan="2" class="submit-btn"><%= t.submit("Submit", class: "btn btn-large btn-dark")%></td>
        </tr>
      </table>
    </div>
  <% end %>
</div>

app/views/email_templates/select.html.erb
<div class="container-fluid no-padding">
  <h1>Please select a template</h1>
</div>

<div class="col-md-12 col-sm-12">
  <div class="table-responsive">
    <div class="col-md-12 scrollable">
      <table class="table template-table">
        <tr>
          <th class="name">Name of Template</th>
          <th class="content">Content Preview</th>
          <th class="details"></th>
        </tr>
        <% @templates.sort_by(&:created_at).reverse.each do |t| %>
          <tr>
            <td class="name"><%= t.name %></td>
            <td class="content"><%= truncate(t.content, length: 80) %></td>
            <td class="details"><%= link_to 'Use this template', new_confirmation_email_path(template_id: t.id, booking_id: @booking_id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/email_templates/show.html.erb
<div class="col-md-12 col-sm-12">
  <div class="btn-container">
    <div><%= button_to("Back To Email Template List", email_templates_path, method: "get", class: "btn btn-large btn-light") %></div>
  </div>

  <div class="table-responsive-lg email-template-table">
    <table>
      <tr>
        <td class="td-container name"><b>Name of Template</b></td>
        <td class="td-container name"><%= @template.name %></td>
      </tr>

      <tr>
        <td class="td-container content"><b>Content</b></td>
        <td class="td-container content"><%= @template.content %></td>
      </tr>
    </table>
  </div>
</div>